[package]
name = "my-csv-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = "1.0.216"
serde_derive = "1.0.216"
anyhow = "1.0.94"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
common_macros = "0.1.1"
